from .schema import (
    ALL_MODELS,
    DB_PATH,
    INDEX_STATEMENTS,
    AppState,
    Attachment,
    BaseModel,
    BudgetEntry,
    BudgetLine,
    Commitment,
    EmailAccount,
    Goal,
    Initiative,
    ItemTag,
    Meeting,
    MeetingAttendee,
    MeetingNote,
    MeetingTemplate,
    Person,
    Project,
    Quarter,
    SchemaVersion,
    Tag,
    WorkItem,
    create_fts_support,
    create_indexes,
    create_tables,
    create_updated_at_triggers,
    create_views,
    db,
    initialize_schema,
)

Task = WorkItem
Note = MeetingNote
TaskTag = ItemTag

__all__ = [
    "ALL_MODELS",
    "AppState",
    "Attachment",
    "BaseModel",
    "BudgetEntry",
    "BudgetLine",
    "Commitment",
    "DB_PATH",
    "EmailAccount",
    "Goal",
    "Initiative",
    "ItemTag",
    "Meeting",
    "MeetingAttendee",
    "MeetingNote",
    "MeetingTemplate",
    "Note",
    "Person",
    "Project",
    "Quarter",
    "SchemaVersion",
    "Tag",
    "Task",
    "TaskTag",
    "WorkItem",
    "create_fts_support",
    "create_indexes",
    "create_tables",
    "create_updated_at_triggers",
    "create_views",
    "db",
    "initialize_schema",
]
