from .page_add_owner import SetupWizardAddOwnerPage
from .page_finish import SetupWizardFinishPage
from .page_import_contacts import SetupWizardImportContactsPage
from .page_import_context import SetupWizardImportContextPage
from .page_set_goals import SetupWizardSetGoalsPage
from .setup_wizard import SetupWizard
